# Generated by Django 3.2.8 on 2024-04-22 10:28

import app_file.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='New folder', max_length=100)),
                ('description', models.TextField(default='')),
                ('permissions', models.CharField(choices=[('0', 'private'), ('1', 'public')], default='0', max_length=10)),
                ('saved', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_file.folder')),
            ],
            options={
                'verbose_name': 'Thư mục',
                'db_table': 'tb_folder',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='New file', max_length=100)),
                ('description', models.TextField(default='')),
                ('file', models.FileField(upload_to=app_file.models.file_upload_to)),
                ('size', models.IntegerField(default=0)),
                ('permissions', models.CharField(choices=[('0', 'private'), ('1', 'public')], default='0', max_length=10)),
                ('saved', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_file.folder')),
            ],
            options={
                'verbose_name': 'Tập tin',
                'db_table': 'tb_file',
            },
        ),
    ]
