# Generated by Django 3.2.8 on 2024-04-25 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_file', '0002_auto_20240425_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saved',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', models.ManyToManyField(null=True, related_name='Saved_file', to='app_file.File')),
                ('folder', models.ManyToManyField(null=True, related_name='Saved_folder', to='app_file.Folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Đã lưu',
                'db_table': 'tb_saved',
            },
        ),
    ]
