# Generated by Django 5.0.4 on 2024-05-10 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0006_requestupgrate_created_at_alter_profile_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestupgrate',
            options={'ordering': ['created_at'], 'verbose_name': 'Yêu cầu nâng cấp'},
        ),
    ]
