# Generated by Django 5.0.4 on 2024-05-13 08:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0007_alter_requestupgrate_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('code', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'Mã xác thực',
                'db_table': 'tb_email_code',
            },
        ),
        migrations.AlterModelOptions(
            name='requestupgrate',
            options={'ordering': ['-created_at'], 'verbose_name': 'Yêu cầu nâng cấp'},
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('0', 'Not actived'), ('1', 'actived')], default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='store',
            field=models.IntegerField(default=10000),
        ),
    ]
