# Generated by Django 3.2.8 on 2024-04-23 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_auto_20240422_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestUpgrate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('0', 'processing'), ('1', 'accepted'), ('2', 'rejected')], default='0', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RequestUpgrate_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yêu cầu nâng cấp',
                'db_table': 'tb_request',
            },
        ),
    ]
