# Generated by Django 3.2.8 on 2024-04-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0004_requestupgrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitaction',
            name='store',
            field=models.IntegerField(default=0),
        ),
    ]
